name: Axon Data Protection Config API

on: [push, pull_request]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 8
          server-id: axoniq-nexus
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and verify
        run: mvn -B -U clean verify

      - name: Deploy to internal nexus
        run: mvn -B -U deploy
        env:
          MAVEN_USERNAME: ${{ secrets.DEVBOT_GITHUB_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DEVBOT_GITHUB_TOKEN }}